trigger:
- main  # Adjust this to your branch name

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu image (can be changed to Windows if needed)

variables:
  mavenOpts: '-Xmx3072m'  # Optional: Adjust if needed for heap size

steps:
# Step 1: Install JDK
- script: |
    sudo apt-get update
    sudo apt-get install openjdk-11-jdk -y  # Install JDK version 11
  displayName: 'Install JDK'

# Step 2: Install Maven
- script: |
    wget https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
    tar -xvzf apache-maven-3.8.6-bin.tar.gz
    sudo mv apache-maven-3.8.6 /opt/maven
    sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn
  displayName: 'Install Maven'

# Step 3: Build the Project with Maven
- script: |
    mvn clean install -DskipTests=false  # Run Maven build
  displayName: 'Build with Maven'

# Step 4: Publish the .jar Artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/target'  # Path to your generated .jar
    ArtifactName: 'SpringBootApp'
    publishLocation: 'Container'
